title: Rooms for Rent in Malaysia

input_file: malaysia_rental_lists.csv

sort_by:
  - Area
  - Rent (RM/month)
  - Location

index: Area

currency: RM

markdown: "Source code can be found [here]({}). Created by [{}]({}), feel free to contact me!"

github: https://github.com/titus-chin/rooms-for-rent-in-malaysia

author: Titus Chin

linkedin: https://www.linkedin.com/in/titus-chin-jun-hong/